version: '2'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: share

  beat:
    build: .
    command: python3 manage.py celery beat -l DEBUG
    depends_on:
      - postgres
      - rabbitmq
    links:
      - rabbitmq
      - postgres
    environment:
      POSTGRES_HOST: postgres
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672/'

  worker:
    build: .
    command: python3 manage.py celery worker -l DEBUG
    depends_on:
      - postgres
      - rabbitmq
    links:
      - rabbitmq
      - postgres
    environment:
      POSTGRES_HOST: postgres
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672/'

  flower:
    build: .
    ports:
      - '5555:5555'
    command: python3 manage.py celery flower
    depends_on:
      - postgres
      - rabbitmq
    links:
      - rabbitmq
      - postgres
    environment:
      POSTGRES_HOST: postgres
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672/'

  monitor:
    build: .
    command: python3 manage.py monitor
    depends_on:
      - postgres
      - rabbitmq
    links:
      - rabbitmq
      - postgres
    environment:
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672/'

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672/'
